[package]
name = "tethys"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-arena = "2.0.1"
chumsky = "0.6.0"
ariadne = "0.1.3"
logos = "0.12.0"
color-eyre = "0.5.11"
tracing-subscriber = "0.3.3"
tracing = "0.1.29"